### ISSUE TITLE
Review Atomic Element fields and determine field validation

### ISSUE THREAD

**Issue by kave** [cfpb/consumerfinance.gov#1258]

**Comment by KimberlyMunoz** [comment]
>Right now we’re not including any `required` fields on the admin side of things and figured at some point we’ll need to talk about what's required for a `Landing Page` etc.

@leejenni and @schaferjh, can we have a working session to hammer this out between BEWDs and Content?

**Comment by schaferjh** [comment]
Yes, we can. Sounds like we need to do this for all page types, right? Perhaps as part of the next sprint?

**Comment by KimberlyMunoz** [comment]
Yep!

**Comment by KimberlyMunoz** [comment]
Just a flag that this meeting didn't happen, but it's okay to move it during our operation & maintanence period after launch

**Comment by richaagarwal** [comment]
Just going through the issues - is this something we still need to discuss?  Or can we provide more context here for other people to pick up?

**Comment by anselmbradford** [comment]
@cfpb/cfgov-backends Is this still an issue?

**Comment by cwdavies** [comment]
Closing this issue as there is not enough context for cfgov-backends.
