### ISSUE TITLE
Streaming selection should require a Go Live Date

### ISSUE THREAD

**Issue by richaagarwal** [cfpb/consumerfinance.gov#1446]
Currently, you can select "Streaming?", but not a "Go Live Date", as shown:

<img width="1062" alt="screen shot 2016-02-11 at 1 59 13 pm" src="https://cloud.githubusercontent.com/assets/354591/12992218/f12ef862-d0c7-11e5-8511-dc1ec304d5eb.png">

and successfully save the page, but it will error out when you try to view the page because there's no Go Live Date. We should add validation here.

Additionally, though it doesn't error out, we should require a URL as well, right? @kave

**Comment by kurtw** [comment]
I'm seeing the date when I enter it in the admin. Steps to reproduce?

**Comment by richaagarwal** [comment]
Sorry, I can see how that was confusing. It's not that you *can't* enter a Date, it's just that if you *don't*, it will crap out without a validation error. That's why it's low priority.

**Comment by cwdavies** [comment]
Unable to reproduce

**Comment by jslay-excella** [comment]
I cant get the 500 (no live start date defined, but event start date in the future, past, present). 

Regardless, I agree with the validation of the ID and start date. 

I have some thoughts:
* If a live video id is defined, shouldn't "streaming" be assumed to be `True`?
* If no live start date is defined, should it just take the start date of the event itself?
