### ISSUE TITLE
On-demand header: make mega menu's search and submit a complaint components optional

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/consumerfinance.gov#2168]
Heads up that the on-demand header will need to be able to generate a (responsive) variant that does not include the search and submit a complaint links (background https://[GHE]/consumer-response/027-Form-3.0/issues/1#issuecomment-78078). Implementation timeframe will be between now and August.

**Comment by Scotchester** [comment]
Note that her comment also says "without nav"

**Comment by anselmbradford** [comment]
Erp, right.. also no nav

**Comment by schaferjh** [comment]
Do they need any part of the header (like the eyebrow?) or is this just a white shape containing the logo and a green stroke?

**Comment by anselmbradford** [comment]
Haha, yes to that description! :) However, the eyebrow will be included, at least as far as the tagline.

**Comment by schaferjh** [comment]
So a variation on the eyebrow? 

I guess I'm wondering if this is a variant of the header, or it's own thing?

**Comment by anselmbradford** [comment]
> So a variation on the eyebrow?

Not sure yet whether the language links will be included or not. I'll update when I know.

> I guess I'm wondering if this is a variant of the header, or it's own thing?

Hmm... I suppose it could go both ways, but since it's components of the header that are hidden as opposed to moving things around, I'd lean toward a variant.

**Comment by Scotchester** [comment]
This variant (just eyebrow with no language links and logo) could conceivably be used for something like You Have the Right campaign-style pages, too.

**Comment by anselmbradford** [comment]
This is live on https://complaint.consumerfinance.gov/submit-a-complaint/s/products now.
