### ISSUE TITLE
Compress images uploaded by Wagtail

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/consumerfinance.gov#2194]
Related to #2175, we should look into doing lossless compression on images uploaded by wagtail.

**Comment by anselmbradford** [comment]
@chosak do you know if this was implemented?

**Comment by chosak** [comment]
@anselmbradford not that I know of. Wagtail does support compression of images in templates, but we're not using that anywhere as far as I know.

**Comment by anselmbradford** [comment]
Thanks!

**Comment by PMARINA** [comment]
@chosak Is this still needed or can this be closed?

**Comment by cwdavies** [comment]
Closing this issue as it is a duplicate of CFGOV/platform/issues/4041
