### ISSUE TITLE
Page number form in filterable list pagination molecule drops parameters

### ISSUE THREAD

**Issue by kurtrwall** [cfpb/consumerfinance.gov#2199]
## Current behavior
- The page number field in the pagination molecule has a `Go` button next to it to go to the page specified in the input. The issue is [here](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/jinja2/v1/_includes/molecules/pagination.html#L63), where the parameters from the filter are made into hidden input fields. If you select multiple options of the same vein, say "Category", then only the last parameter in the URL will be used.
- Much less worrisome but still a bug, the last page visited number is maintained in the URL if using that "Go" form.
## Expected behavior
- All parameters should be maintained when going to different pages using the "Go" form.
- The page parameter in the URL should be singular and be the current page visited.
## Steps to replicate behavior
1. Select two or more "Categories" on Blog and filter the results.
2. Scroll to the bottom where the pagination molecule is and increment the number and hit "Go"
3. Note that the URL only contains the last category selected, it's not selected in the filter anymore, and there are 2 page parameters in the URL

@anselmbradford was the one that first reported the duplicated `page` parameter.

**Comment by anselmbradford** [comment]
Reproduced in https://[GHE]/CFGOV/platform/issues/2681
