### ISSUE TITLE
Analytics.init() called before associated test

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/consumerfinance.gov#2361]
## Current behavior
- `Analytics.init()` test calls init https://github.com/cfpb/consumerfinance.gov/blob/e30d3ac6cb05c7184863f699bffb506db2520163/test/unit_tests/js/modules/Analytics-spec.js#L52, but it has already been called before the test in https://github.com/cfpb/consumerfinance.gov/blob/e30d3ac6cb05c7184863f699bffb506db2520163/test/unit_tests/js/modules/Analytics-spec.js#L1 because of https://github.com/cfpb/consumerfinance.gov/blob/e30d3ac6cb05c7184863f699bffb506db2520163/cfgov/unprocessed/js/modules/Analytics.js#L92
## Expected behavior
- Method should not be called before it is tested.
## Steps to replicate behavior
1. `xit` Analytics tests and `Analytics.init()` is still called.

**Comment by sebworks** [comment]
It's just testing that the state is properly set, when init is called,  with and without a defined `window.google_tag_manager` value.  The `google_tag_manager` value should be `undefined` when `Analytics.js` is required ( init is automatically called when it's required ). I then set the `google_tag_manager` value, and call init again.

**Comment by anselmbradford** [comment]
That makes sense. The one recommendation I'd have is to not call the external API internally without user input. So instead of calling `Analytics.init();` [here](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/js/modules/Analytics.js#L87), use lazy instantiation to call it when it's actually needed by adding:
```
if ( typeof Analytics.tagManagerIsLoaded !== 'boolean' ) {
  Analytics.init();
}
```
…to [this line](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/js/modules/Analytics.js#L55) and removing [this line](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/js/modules/Analytics.js#L7) (or set it to `standardType.UNDEFINED`).

That way the state of the Analytics object will always be the same when it is required, independent of the page's state and the external API can be tested before it's ever called once.
