### ISSUE TITLE
Add icon meta field to beta categories

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/consumerfinance.gov#256]
As the use of the `category_icon` macro expands (I am currently [adding it to the events hero](https://github.com/cfpb/cfgov-refresh/pull/255/files#diff-c3d88a5876a4637acb70fdac18ee2b82R11)) the ~~[logic controlling the appropriate icon](https://github.com/cfpb/cfgov-refresh/blob/gh-pages/_includes/post-macros.html#L20-L38)~~ may become quite complex. 

We should consider adding an icon meta field to the beta categories (and eventually event categories as they're created) to remove the logic from the macro.

**Comment by KimberlyMunoz** [comment]
This is still an issue in wagtail, but it could be fixed with a refactoring. It's probably low priority.

**Comment by jimmynotjim** [comment]
This has moved but it's still there https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/macros/category-icon.html

**Comment by jimmynotjim** [comment]
After discussing with Scott and looking at all the places this is implemented, this isn't quite as simple any more. Would still love to see the logic moved out of the templates, but not sure it should be a high priority compared to a lot of other work we have waiting.

**Comment by anselmbradford** [comment]
This looks to have been fixed by https://github.com/cfpb/consumerfinance.gov/commit/58de811f7cb18f88203d1a0f358dee73df5cf1f4
