### ISSUE TITLE
Remove redundant breadcrumbs.html

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/consumerfinance.gov#2638]
## Current behavior

- Identical macros https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/breadcrumbs.html and https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/molecules/breadcrumbs.html exist.

## Expected behavior

- Only https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/molecules/breadcrumbs.html should exist and references the older https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/breadcrumbs.html  should be removed.

**Comment by sebworks** [comment]
There is some difference in macro workings and I don't think it's worth it to address until all the pages are migrated to Wagtail. There is an existing TODO for that here: https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_layouts/content-base-main-first.html#L4.

**Comment by anselmbradford** [comment]
PR --> https://github.com/cfpb/consumerfinance.gov/pull/6437
