### ISSUE TITLE
Email signup abbr and wonky with defaults

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/consumerfinance.gov#3233]
The email signups uses some abbreviations in the UI, which it probably shouldn't and it doesn't show the default input properly.

## Current behavior

- Email signup includes `Gd code`, what is this? How's the user supposed to know?
- It also includes `Btn text`, which should probably be expanded to `Button text`.

![screen shot 2017-08-09 at 1 44 33 pm](https://user-images.githubusercontent.com/704760/29179043-4c8a8332-7dc1-11e7-8445-6a7012b3d9aa.png)

- Also, the `Type` input defaults to `---------`, which if is not changed appears to end up as a text input type, which begs the question of why the default is not just `Text` to begin with?

![screen shot 2017-08-09 at 1 49 57 pm](https://user-images.githubusercontent.com/704760/29179054-5507eb6c-7dc1-11e7-8751-f95e5acf9d07.png)

## Expected behavior

- Abbreviations are spelled out.
- Default input type is set in the `Type` drop-down.

## Steps to replicate behavior

1. Create a new blog page in wagtail.
2. Add an email signup component.

**Comment by lerenah** [comment]
I'd like to work on this.

**Comment by anselmbradford** [comment]
Opening any issues around difficulties in getting the project set up is helpful too. Thanks!

**Comment by jslay-excella** [comment]
This appears to be stale and no longer an issue with the current version of cfgov. Please reopen if I have misunderstood something. 

Steps I took:
* Add new blog page
* Add email signup component

![image](https://user-images.githubusercontent.com/59629491/155858312-625d0dfe-a1f2-4465-bc4e-2c28027f3fae.png)
