### ISSUE TITLE
Snippet List: Tags is required, but not designated as so with an asterisk

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/consumerfinance.gov#3244]
## Current behavior

- The "tags" on a snippet list are required, but unlike other required elements within a snippet list are not marked with an asterisk.

## Expected behavior

- All required elements are styled the same (marked with an asterisk in this case).

## Steps to replicate behavior

1. In wagtail add a snippet list and hit save without entering in any info. See that the tags are required, but that's not clear before hitting save.

## Screenshots

__Current__

<img width="939" alt="screen shot 2017-08-14 at 2 08 20 pm" src="https://user-images.githubusercontent.com/704760/29284851-55240bc6-80fa-11e7-8ac3-e56255d9f38b.png">

**Comment by anselmbradford** [comment]
Unrelated, but the `Enter tag names…` helper text is also indented too far.

**Comment by jslay-excella** [comment]
This has been fixed in [#9319](https://github.com/wagtail/wagtail/pull/9319) and is apart of the 4.1 release.

**Comment by anselmbradford** [comment]
Confirmed this is fixed

<img width="846" alt="Screen Shot 2023-06-13 at 9 14 06 AM" src="https://github.com/cfpb/consumerfinance.gov/assets/704760/474eb115-5502-40be-9b66-1f69259a92e5">
