### ISSUE TITLE
Sauce window dimensions are not being set

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/consumerfinance.gov#3527]
## Current behavior

- Running tests on sauce shows up `undefined,undefinedpx` because [this reference does not exist anymore](https://github.com/cfpb/cfgov-refresh/blob/master/test/browser_tests/conf.js#L183-L184):
```js
                        environmentTest.windowWidthPx + ',' +
                        environmentTest.windowHeightPx ) + 'px';
```

## Expected behavior

- Running tests on sauce should display the window dimensions that are being run, which will be either a default or the custom dimensions set in the `--windowSize=x,y` flag.

## Steps to replicate behavior

2. In cfgov-refresh, set `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` in your `.env` file (see "Finding Your Username and Access Key" in the [Sauce docs](https://wiki.saucelabs.com/display/DOCS/Account+Methods)).
3. Re-source your `.env` file with `. .env` while in the project root directory.
2. Run `gulp test:acceptance --sauce`. It should output `Sauce Connect is up, you may start your tests.` just before the tests start on Sauce.
1. Log into saucelabs.com
3. View the [Automated Tests Sauce dashboard](https://saucelabs.com/beta/dashboard/tests) and see that the window dimensions are reported as `undefined` (you may need to resize the window to see the full output string. See screenshot). 

## Screenshots

__Current__

<img width="514" alt="screen shot 2017-10-28 at 3 07 01 pm" src="https://user-images.githubusercontent.com/704760/32137633-b10d2c24-bbf1-11e7-9cb2-0e6003565fe1.png">

**Comment by anselmbradford** [comment]
Lets make the output look like `1200px × 900px` (that's https://en.wikipedia.org/wiki/Multiplication_sign, not an 'x')

**Comment by jotasprout** [comment]
Does this still need to be done?

**Comment by anselmbradford** [comment]
@jotasprout Yup, just confirmed it's still an issue. I've also updated the replicate instructions.

**Comment by jotasprout** [comment]
@anselmbradford Can you please clarify what "this reference does not exist anymore" means? If I understand what I'm looking at in conf.js and environment-test.js, everything is declared and called like it should be. Or is this task more complicated than it seems and I should just fork, clone, etc.? Sorry if that's a ridiculously stupid question.

**Comment by anselmbradford** [comment]
`environmentTest.windowWidthPx` and `environmentTest.windowHeightPx` were once set in `environment.js` https://github.com/cfpb/cfgov-refresh/commit/0bc9e314989cafee92cf0d565d9b90f71ec0f692#diff-e23f246b2cf619981196c59b9b3afd49R27, but [that was later deleted](https://github.com/cfpb/cfgov-refresh/commit/93300435932a837763645b442f2e54854e94ce32#diff-671f6edb2c8e64039434f833b41c6546L24), so now they'll always be `undefined`, so the values there will need to be the browser default in Sauce, which off the top of my head I'm not sure what that is, so that's what needs to be determined.

**Comment by cwdavies** [comment]
Closing this issue as you now get: `Task never defined: test:acceptance` and cypress is now being used to run browser tests.
