### ISSUE TITLE
Outdated code job link

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/consumerfinance.gov#3531]
## Current behavior

- [This code comment](https://github.com/cfpb/cfgov-refresh/blob/899a249b70c93743dafe3b23f1ba60aa5e128be4/cfgov/jinja2/v1/_layouts/base-common.html#L19) links to https://www.consumerfinance.gov/jobs/technology-innovation-fellows/, which contains outdated job links and info about fellows who are no longer with the bureau.

## Expected behavior

- https://www.consumerfinance.gov/jobs/technology-innovation-fellows/ is worded to reflect the current workforce and opportunities at the bureau.

**Comment by csebianlander** [comment]
The page in question, which was both wildly out of date and not linked to anywhere else on CF.gov except on a legacy blog post circa 2015, has been unpublished and now redirects to "Careers at the CFPB," so users will not be directed to outdated information. Up to the dev team whether to update the URL in that code comment or to leave as is now that it ultimately leads somewhere more current.
