### ISSUE TITLE
Update favicon code

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/consumerfinance.gov#3662]
[Favicon code](https://github.com/cfpb/cfgov-refresh/blob/582f0ac9b9c334d32228f02654ec2385c70db30c/cfgov/jinja2/v1/_layouts/base-common.html#L102) could utilize more modern approaches --> https://github.com/audreyr/favicon-cheat-sheet

**Comment by thumbsupep** [comment]
I would love to help with this! I added the favicon code for godaddy.com (I'm an SDE at GoDaddy)

**Comment by Scotchester** [comment]
@thumbsupep That'd be great!

The link to the current code that Ans posted is a little out of date. It now lives at https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/jinja2/v1/_layouts/base.html#L108.

I can get you a source file to work with for creating the various sizes. What design software do you have access to?

**Comment by thumbsupep** [comment]
so sorry I dropped the ball on this! Unfortunately I dont have design software; I was given a png and an svg and was able to generate the necessary .ico, xml, json, and various sized pngs using https://realfavicongenerator.net/ and https://www.favicon-generator.org/ if you're comfortable having your logo uploaded on those sites...

**Comment by anselmbradford** [comment]
2021 guide https://medium.com/web-dev-survey-from-kyoto/favicon-nightmare-how-to-maintain-sanity-7628bfc39918

**Comment by herewegoagain2** [comment]
> [Favicon code](https://github.com/cfpb/cfgov-refresh/blob/582f0ac9b9c334d32228f02654ec2385c70db30c/cfgov/jinja2/v1/_layouts/base-common.html#L102) could utilize more modern approaches --> https://github.com/audreyr/favicon-cheat-sheet
> 
>
