### ISSUE TITLE
Move browser tests to localhost:8000 with test pages in CMS

### ISSUE THREAD

**Issue by contolini** [cfpb/consumerfinance.gov#5030]
Set up cfgov-refresh to run against a local database. For browser tests but also other things. This issue is a WIP. It's @Scotchester's problem.

**Comment by contolini** [comment]
JK ~~we're~~ @Scotchester is now doing https://code.djangoproject.com/wiki/Fixtures

**Comment by contolini** [comment]
Also: We are henceforth referring to our browser tests as "cross browser tests" to differentiate them from integration tests.

**Comment by cfarm** [comment]
I just successfully ran the feedback form tests against my localhost using the following steps:

1. Created a new wagtail page locally at `/test-feedback-form`
1. Edited the `feedback-form.feature` file to point to `/test-feedback-form`
1. Make sure the feedback-form browser test files are in the `cucumber-new` folder from #4472

**Comment by cwdavies** [comment]
Closing this 2 year old issue as cypress is now being used and cucumber tests have been deleted.

**Comment by Scotchester** [comment]
It should be noted that the root of this issue is still something that needs to be done for the new Cypress tests, but I think that's being tracked elsewhere.
