### ISSUE TITLE
IRegs - Small search terms return too many results from ES

### ISSUE THREAD

**Issue by jslay-excella** [cfpb/consumerfinance.gov#6468]
When a user enters a search query that is too generic or small, ES results window exceeds the set limits, causing an Internal Server Error.

## Current behavior

- User enters a small/generic search term (i.e. "the")
- ES raises exception with
```
elasticsearch7.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'Result window is too large, from + size must be less than or equal to: [10000] but was [14728]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.')
```

## Expected behavior

- No search is performed when small/generic search terms OR gracefully handles too many results and returns such error.

## Steps to replicate behavior

1. Search "the" on [IRegs Search](https://www.consumerfinance.gov/rules-policy/regulations/search-regulations/).

**Comment by niqjohnson** [comment]
I moved this one over to our backlog.
