### ISSUE TITLE
TDP: uses abandoned aos dependency

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/consumerfinance.gov#7655]
TDP: uses abandoned aos npm package ([here](https://github.com/cfpb/consumerfinance.gov/blob/ba006e9182530f96b85e0eb47f93f27243efedbb/cfgov/unprocessed/apps/teachers-digital-platform/js/index.js#L16) and as the `data-aos` flag in [bb-tool](https://github.com/cfpb/consumerfinance.gov/blob/ba006e9182530f96b85e0eb47f93f27243efedbb/cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/bb-tool.html)), which hasn't been updated in 5 years https://github.com/michalsnik/aos

This library installs `classlist-polyfill`, `lodash.debounce`, and `lodash.throttle` as dependencies.

We might want to just copy the parts of AOS we use and ditch the library.

**Comment by wpears** [comment]
This was removed when we sunset the tdp journey app
