### ISSUE TITLE
Whitelist external requests for Sauce Connect

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/consumerfinance.gov#886]
See whitelist section on https://docs.saucelabs.com/reference/sauce-connect/#how-can-i-improve-performance-
Domains like `youtube.com`, `quantserve.com`, and `doubleclick.net` should be whitelisted so they're accessed directly vs going through the Sauce Connect VPN.

**Comment by cwdavies** [comment]
@anselmbradford Can this issue be closed if sauce-connect has domains whitelisted?

**Comment by anselmbradford** [comment]
We're not currently utilizing sauce in the consumerfinance.gov repo, so we can close for the same reasoning as https://github.com/cfpb/consumerfinance.gov/issues/888 and https://github.com/cfpb/consumerfinance.gov/issues/3527
