### ISSUE TITLE
Create window Resize module with throttle param

### ISSUE THREAD

**Issue by sebworks** [cfpb/consumerfinance.gov#906]
Currently we are creating multiple resize listeners in various files. It can be expensive when resizing without throttling callbacks ( https://developer.mozilla.org/en-US/docs/Web/Events/resize ).

Some places where we are using the resize event: 
- `secondary-nav-toggle.js`
- BreakpointHandler instances.

**Comment by cwdavies** [comment]
Closing this issue as I am unable to find a file called `secondary-nav-toggle.js` in the consumerfinance.gov code base.
