### ISSUE TITLE
Work out use of underscore in JS in this repo and document in front-end standards

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/consumerfinance.gov#919]
As we grow our JS it would be good to work out in FEWD standards how we use underscore-prefixed names, as it's not entirely clear currently.

My understanding of the underscore convention is:

> Use an underscore to designate a variable or function in the export scope (the nesting level where module.exports is called) as private, _except if it's used to refer to an imported class or third-party naming convention (jquery, lodash, etc.)._

That last bit is where it becomes unclear. Do imported packages that are not using a convention or are not a class get an underscore or not? We use both conventions:

[underscore imports](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/beta-banner-state.js#L9-L10)
[underscore imports](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/jquery/cf_formValidator.js#L7-L9)
[underscore imports](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/util/date-range-formatter.js#L7-L10)
[underscore imports - _well, actually `handlebars` is almost definitely a convention_](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/external-site.js#L8-L9)

[no underscore imports](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/post-filter.js#L8-L9)
[no underscore imports](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/youtube.js#L8-L10)
[no underscore imports](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/classes/MobileCarousel.js#L7-L10)
[no underscore imports](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/classes/MobileOnlyExpandable.js#L3-L6)
[no underscore imports](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/jquery/type-and-filter.js#L12-L13)
[no underscore imports](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/routes/careers/current-openings/index.js#L7)
### Underscore

Pro: Makes it consistent with how other variables are used.
Con: Things like `var handlebars` are not clear on their convention.
### No underscore

Pro: Makes all imported modules consistently not use underscores. A variable without an underscore is either: an imported module, a function parameter, or a local variable.
Cons: Not consistent with how other variables that don't get exported are defined in the export level scope.

Example file:

```
var $ = require( 'jquery' ); // No underscore needed b/c it uses a well-established convention name.
var Widget = require( 'Widget' ); // No underscore needed b/c it's a class instantiated with `new`.

var pkg = require( 'pkg' ); // No underscore needed b/c it's a third-party package to this module, name follows filename.

// or

var _pkg = require( 'pkg' ); // Underscore needed b/c it's a third-party package that doesn't have an established convention and it's not being exported.

var _globalVar = true; // Underscore needed b/c it's in the module.exports scope.

// Underscore needed for `_helper` b/c it's in the module.exports scope,
// no underscored needed for `thing` b/c it's in a local scope.
function _helper( thing ) {
    // private api implementation.
   var localVar = new Widget(); // No underscore needed b/c it's in the scope of _helper.
}

function Example() { // No underscore, b/c it's exported publicly.
    // public api implementation.
   _helper( 'stuff' );
}

module.exports = Example;
```

Which convention seems best to you?

**Comment by anselmbradford** [comment]
The browser tests are also a mix of the two styles.

**Comment by cwdavies** [comment]
@anselmbradford Has the use of underscore in JavaScript been documented in front-end standards? Can this issue be closed?

**Comment by anselmbradford** [comment]
> Has the use of underscore in JavaScript been documented in front-end standards? Can this issue be closed?

It has not, but I've moved this issue to our development standards repo https://github.com/cfpb/development/issues/214
